language: java

addons:
  sonarcloud:
    organization: "fredboat"

env:
  global:
    - BUILD_NUMBER: "$TRAVIS_BUILD_NUMBER"

cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.gradle"
    - ".gradle/wrapper"
    - ".gradle/caches"
    - "$HOME/.sonar/cache"

stages:
  - sonar

jobs:
  fast_finish: true
  include:
    - stage: sonar
      jdk: openjdk10
      before_script:
        #for full sonar cloud blame information
        - "git fetch --unshallow"
      script:
        - "./gradlew sonarqube -PincludeAnalysis"
