name: Build

on:
  push:
    branches: [ '**' ]
    paths-ignore: [ '**.md' ]
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
      DOCKERHUB_TOKEN:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 13
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Lavalink.jar
          path: LavalinkServer/build/libs/Lavalink.jar

      - name: Docker Meta
        if: env.DOCKERHUB_USERNAME && env.DOCKERHUB_TOKEN
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            fredboat/lavalink
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha,prefix=

      - name: Set up QEMU
        if: env.DOCKERHUB_USERNAME && env.DOCKERHUB_TOKEN
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        if: env.DOCKERHUB_USERNAME && env.DOCKERHUB_TOKEN
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: env.DOCKERHUB_USERNAME && env.DOCKERHUB_TOKEN
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and Push
        if: env.DOCKERHUB_USERNAME && env.DOCKERHUB_TOKEN
        uses: docker/build-push-action@v3
        with:
          file: LavalinkServer/docker/Dockerfile
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
